### ISSUE TITLE
feat: 플레이어 탄환 발사 로직 수정

### ISSUE THREAD

**Issue by HYOJEONG0213** [PLUM-NCL/Never-Come-Lab#12]
## What is this issue? 🚀
플레이어가 보는 방향에 따라 탄환 발사되게끔 수정

## TODO 🏃‍♀️
- [x] 총알 자동 발사
- [x] 보는 방향에 따라 탄환 발사 
- [x] 한번 더 누르면 총알 On / Off
- [x] 버튼 on off 색상 바꾸기
- [x] 총알 위치 버그 수정 
- [x] 벽 바로 앞에서 발사시 총알이 생성되는 버그
