### ISSUE TITLE
feat: 플레이어 HP, 데미지, 바인드 기능 연결하기

### ISSUE THREAD

**Issue by HYOJEONG0213** [PLUM-NCL/Never-Come-Lab#22]
## What is this issue? 🚀
플레이어 HP, 데미지, 바인드 기능 연결하기

## TODO 🏃‍♀️
- [x] 플레이어 HP UI 제작
- [x] 몬스터에게 데미지 입는 로직
- [x] 데미지 입은 효과 
- [x] 바인드총과 몬스터 바인드 기능 연결하기
