### ISSUE TITLE
feat: 레버 당기기 로직 추가 

### ISSUE THREAD

**Issue by HYOJEONG0213** [PLUM-NCL/Never-Come-Lab#34]
## What is this issue? 🚀
레버 당기기 로직 추가

## TODO 🏃‍♀️
- [x] 레버 당기기 애니메이션 코드 추가
- [x] 레버에 따라 길이 생성, 삭제 되는 로직 추가
- [x] 레버에 따라 벽이 생성, 삭제 되는 로직 추가
- [x] 애니메이션 버그 수정
- [x] 탄환 버그 수정
- [x] 마우스 레버에 누르면 우다다다 열리는 버그 수정 
- [x] 레버 기능 추가(시간 지나면 자동 닫침, 한번 누르면 원상복구 불가, 왔다갔다 자유롭게 가능, 가짜레버..)
