### ISSUE TITLE
feat: 인게임 UI 수정 및 추가 구현

### ISSUE THREAD

**Issue by YohanIm00** [PLUM-NCL/Never-Come-Lab#35]
## What is this issue? 🚀
기존 인게임 UI의 디자인을 수정하고 추가 기능을 개발합니다.

## TODO 🏃‍♀️
- [x] 기존 버튼 디자인 수정
- [x] 플레이어 체력 바 수정
- [x] 플레이어 페이스 패널 추가
- [x] 무기 버튼 이미지 변경
