### ISSUE TITLE
feat: 리트 기능 추가

### ISSUE THREAD

**Issue by HYOJEONG0213** [PLUM-NCL/Never-Come-Lab#45]
## What is this issue? 🚀
플레이어가 죽은 뒤 게임오버! 재시작 하시겠습니까? 창 만들기

## TODO 🏃‍♀️
- [x] 플레이어가 죽는 애니메이션/소리 추가
- [x] 죽었을 때 상호작용 끄기 
- [x] 죽은 뒤 재시작 창 만들기(예 -> 해당 신 다시 호출, 아니오 -> 메인화면으로 돌아가기) 
- [x] 바로 직전 신으로 연결시키기 
- [x] 메인신 연결시키기 
- [x] 화면 전환 효과 주기
- [ ] 게임오버신에서 fade 효과 안되는 오류 존재함 
- [x] 부활시 체력이나 기타 버그 수정 
- [x] 플레이어가 살아있을 때 ESC 눌러서 재시작, 메인화면으로 ui 띄우기
