### ISSUE TITLE
feat: 1 스테이지 개발

### ISSUE THREAD

**Issue by Sungtae124** [PLUM-NCL/Never-Come-Lab#51]
## What is this issue? 🚀
1스테이지 개발

## TODO 🏃‍♀️
- [x] 기존 기능들 복구
- [x] 몬스터 공격 옮기기 + 배치
- [x] 세부 스테이지 별 대화형 튜토리얼 진행
