### ISSUE TITLE
chore: 게임 UI 세부 수정

### ISSUE THREAD

**Issue by YohanIm00** [PLUM-NCL/Never-Come-Lab#58]
## What is this issue? 🚀
메인 화면과 인게임의 UI를 수정합니다.

## TODO 🏃‍♀️
- [x] 메인 화면 타이틀(demo) 추가
- [x] 인게임 화면 페이스칩(demo) 추가
- [x] 인게임 화면 사운드 교체_탄환 발사음
- [x] 탄알 Prepap 이미지 교체
- [x] Weapon.cs, Bullet.cs의 수치 조정
- [x] 서브 메뉴 이미지 수정
