### ISSUE TITLE
chore: 게임오버 화면 구현 및 효과음 설정

### ISSUE THREAD

**Issue by YohanIm00** [PLUM-NCL/Never-Come-Lab#67]
## What is this issue? 🚀
게임 오버와 구동 신을 디자인하고 효과음을 추가합니다.

## TODO 🏃‍♀️
- [x] 게임 오버 화면 디자인
- [ ] 실행 시 첫 화면 디자인
- [ ] 메인 화면 사운드 추가_효과음
- [ ] 인게임 화면 사운드 추가_효과음
